### ISSUE TITLE
Support config parameters

### ISSUE THREAD

**Issue by edno** [edno/codeception-gherkin-param#2]
Extend parameter support to Codeception config data
```gherkin
Given a configuration file .yml
  """
  actor: Tester
  paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
  settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 2048M
    strict_xml: true
    my_param:
      - user: 'mylogin'
      - password: 'mypassword'
  """
  When I write a scenario using the with a parameter "{{settings['my_param']['user']}}"
  Then the value of "{{settings['my_param']['user']}}" should be "mylogin"
```

**Comment by edno** [comment]
Feature available in **branch 0.3.0** from commit 8245a90e654025a2aba4390d4e58d29ea8827306

Syntax has been modified for being closest to yaml notation and less ambiguous.
Example:
```yaml
settings:
    my_param:
      user: 'mylogin'
      password: 'mypassword'
```
```gherkin
I should see "{{config:my_param:user}}" equals "mylogin"
```

The current code may failed with following yaml config:
```yaml
settings:
    my_param:
      - user: 'mylogin'
      - password: 'mypassword'
```
```gherkin
I should see "{{config:my_param:0:user}}" equals "mylogin"
```

**Comment by edno** [comment]
Other edge case:
```yaml
settings:
    my_param:
      0 : 'mylogin'
```
